name: Deploy Blog
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install and Build
        run: |
          npm i
          npm run build
          npm run export
          touch ./out/.nojekyll
        env:
          AuthorizationToken: ${{ secrets.AUTHORIZATIONTOKEN}}
          RepositoryOwner: JunQu
          RepositoryName: blog
          PageSize: 100

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: out
